{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-default-simulator-{{ version }}.tar.gz
  sha256: 2d8329202b2d9b01df06b58f42d3fe4572d839f792e623145f991298f1676119

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - amazon-braket-schemas >=1.10.1
    - antlr4-python3-runtime ==4.8
    - numpy
    - opt-einsum
    - python >=3.7
    - scipy

test:
  imports:
    - braket
    - braket.default_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
